Signup page
bounswe/bounswe2023group9 pull request #282
Opened 2023-10-16 21:54 UTC by Brunettow

Overflow errors are handled in sign-up page and login page,
Small change in strong password check messages (Messages are now started to be showed when password box is clicked)

2023-10-16 21:57 UTC, omerfaunal commented
Logic in Auth files are not yet ready. Those tasks assigned to @defabdullah. We need to wait for his commits before merging.

2023-10-17 12:38 UTC, omerfaunal requested changes

2023-10-17 12:38 UTC, omerfaunal commented on project/FrontEnd/collaborative_science_platform/lib/screens/login_page.dart
> +        errorMessage = "Password is wrong.";
Change this as Password or username is wrong.

2023-10-17 12:38 UTC, omerfaunal commented on project/FrontEnd/collaborative_science_platform/lib/screens/signup_page.dart
> +                                onChanged: null,
Add onchanged strategy as checking if all criteria are matched.

2023-10-17 12:38 UTC, omerfaunal commented on project/FrontEnd/collaborative_science_platform/lib/widgets/app_button.dart
> +
Add bool isActive

2023-10-17 12:38 UTC, omerfaunal commented on project/FrontEnd/collaborative_science_platform/lib/widgets/app_button.dart
> +        backgroundColor: AppColors.primaryColor,
If button is not active make its color grey[600]

2023-10-17 12:38 UTC, omerfaunal commented on project/FrontEnd/collaborative_science_platform/lib/widgets/strong_password_checks.dart
> +        atLeastOneNumberIsPresent && atLeastOneSpecialCharacterIsPresent;
Check if confirm and normal password are matched

2023-10-17 13:27 UTC, omerfaunal approved these changes

2023-10-17 13:29 UTC, mehmetSuzer approved these changes
ı tested this code in my environment. It looks nice! There is no problem as far as I see.

2023-10-17 13:30 UTC, merged