Mobile workspace
bounswe/bounswe2023group9 pull request #463
Opened 2023-11-19 21:13 UTC by mehmetSuzer

The design of the mobile workspace pages and the navigations between them are implemented without providers. 
The models of @Zulalm are used in the implementation.
Once the providers are implemented, the pages will be updated accordingly.

2023-11-19 21:25 UTC, mehmetSuzer commented
### Some Additional Changes That I Made

1. Since there are many pages which cannot be accessed without logging in, I parametrized the PleaseLoginPage. It takes a message. Different messages can be displayed for different pages. 

2. Files for creating workspace pages are added, but they do not function yet.

3. PageWithAppBar takes a FloatingActionButton now. In default case, there is no FloatingActionButton .

4. I turned AccountSettingsAppBar into a parametrized widget named SimpleAppBar(message).

2023-11-20 11:29 UTC, Zulalm requested changes
The design of the page is looks good but I have some minor comments to improve UX. Bold black text style is not easy to read on a dark blue surface. Also, I think we should not use primary color on all clickable entries. We should use the primary color for the clickable objects that we want to get attention of the user. However, these are only design choices we may discuss them.

2023-11-20 11:29 UTC, Zulalm commented on project/FrontEnd/collaborative_science_platform/lib/screens/workspaces_page/workspaces_page.dart
Since there is not a web workspaces page, this file also should be updated accordingly.

2023-11-20 12:57 UTC, laylaylo submitted a review, later dismissed

2023-11-20 12:57 UTC, laylaylo commented on project/FrontEnd/collaborative_science_platform/lib/models/annotation_text.dart
I realized this since I got the same import error for annotation text.
Please don't include this file as @omerfaunal moved it to widgets directory, instead change import path in models/annotation.dart

2023-11-20 22:42 UTC, mehmetSuzer commented on project/FrontEnd/collaborative_science_platform/lib/main.dart
> +    setUrlStrategy(const PathUrlStrategy());
It does not cause any problem in my Android emulator. Testing the code in Chrome might be the problem.

2023-11-20 22:43 UTC, mehmetSuzer commented on project/FrontEnd/collaborative_science_platform/lib/models/annotation_text.dart
OK, I changed the path of the import.

2023-11-20 22:46 UTC, mehmetSuzer commented
I changed the colors of the widgets, removed unnecessary files, modified the path of annotationText, changed the weight of the texts.

I also fixed an overflow bug in the graph mobile page.

Now, the user him/herself is automatically added to the list of contributors in the workspace.

2023-11-21 10:12 UTC, Zulalm approved these changes

2023-11-21 10:28 UTC, omerfaunal approved these changes
Changed file structure, and everything seems OK

2023-11-21 10:31 UTC, merged