Settings provider
bounswe/bounswe2023group9 pull request #482
Opened 2023-11-21 13:45 UTC by Brunettow

Provider for Settings Preferences Implemented
Provider for Change Password Implemented

- Dummy token is used, will be changed after token part is implemented
- Actions due to response messages not handled

2023-11-25 22:26 UTC, omerfaunal requested changes

2023-11-25 22:26 UTC, omerfaunal commented on project/FrontEnd/collaborative_science_platform/lib/providers/settings_provider.dart
> +  Future<void> changePassword(String oldPass, String newPass) async {
Here changePassword should take User user as argument.
changePassword(User user, String oldPass, String newPass)

2023-11-25 22:26 UTC, omerfaunal commented on project/FrontEnd/collaborative_science_platform/lib/providers/settings_provider.dart
> +      'Authorization': 'Token $token',
And here we should use user.token 

Before merging let's fix this. 

I know instead you used dummy token but still this is not a good usage. Instead setting user.token to something dummy is a better approach. 

For now don't add anything dummy, just add user.

2023-11-25 22:26 UTC, omerfaunal commented on project/FrontEnd/collaborative_science_platform/lib/providers/settings_provider.dart
> +  Future<void> changePreferences(String bio, bool sendNotification, bool showActivity) async {
Same here. User user

2023-11-25 22:26 UTC, omerfaunal commented on project/FrontEnd/collaborative_science_platform/lib/providers/settings_provider.dart
> +      'Authorization': 'Token $token',
user.token

2023-11-25 22:26 UTC, omerfaunal commented on project/FrontEnd/collaborative_science_platform/lib/screens/profile_page/widgets/account_settings_form.dart
> +      await settingsProvider.changePreferences(aboutMeController.text, isSwitched, isSwitched2);
Provider.of<Auth>(context, listen: false).user;

2023-11-25 22:26 UTC, omerfaunal commented on project/FrontEnd/collaborative_science_platform/lib/screens/profile_page/widgets/change_password_form.dart
> +        final settingsProvider = Provider.of<SettingsProvider>(context,listen: false);
Provider.of(context, listen: false).user;

2023-11-27 18:25 UTC, Brunettow commented
Thank you for all the comments. I changed the code accordingly. I also added error and response messages for creating more a responsive page. There are also minor design changes.

2023-11-27 18:30 UTC, omerfaunal approved these changes

2023-11-27 18:30 UTC, merged