provider is implemented for workspace
bounswe/bounswe2023group9 pull request #502
Opened 2023-11-25 21:21 UTC by Zulalm

A provider is implemented for the workspace page. Web and mobile workspaces is updated to have 2 arguments: workspace and workspaces. Get functions for workspace are tested and work well. Token field is added to the auth provider since it is needed for createWorkspace API call.

2023-11-25 21:37 UTC, omerfaunal requested changes

2023-11-25 21:37 UTC, omerfaunal commented on project/FrontEnd/collaborative_science_platform/lib/exceptions/workspace_exceptions.dart
It's really good and useful to have specific exceptions for each case. Nice work here

2023-11-25 21:37 UTC, omerfaunal commented on project/FrontEnd/collaborative_science_platform/lib/providers/workspace_provider.dart
> +      "content-type": "application/json"
Shouldn't we add user token here? If not something wrong with backend. Workspace API should be protected with Auth (user token)

2023-11-25 21:37 UTC, omerfaunal commented on project/FrontEnd/collaborative_science_platform/lib/providers/workspace_provider.dart
> +      "content-type": "application/json"
Same comment as previous

2023-11-25 21:37 UTC, omerfaunal commented on project/FrontEnd/collaborative_science_platform/lib/providers/workspace_provider.dart
> +      "Accept": "application/json",
Same comment as previous

2023-11-25 21:37 UTC, omerfaunal commented on project/FrontEnd/collaborative_science_platform/lib/providers/workspace_provider.dart
> +      "Accept": "application/json",
Same comment as previous. Token issue

2023-11-25 21:40 UTC, omerfaunal commented
My comment about these changes:

All of the endpoints in Workspace should be protected by token. User who has no permission shouldn't see or edit anything  in Workspaces that belongs to another user.

What happens if I copy endpoint and send a request not from an app, from script or something? Any Post request that changes DB or any get request shows privileged information should be protected.

fyi @ArslanArdavic @hakanaktas0

2023-11-25 22:12 UTC, hakanaktas0 commented
We plan to require session token on all post requests after the customer milestone.

2023-11-27 09:21 UTC, mehmetSuzer commented
As @hakanaktas0 said, the session token will be implemented later. Therefore, you may skip these parts for now. After the tokens are implemented in the backend, we can revise the providers. Also, there are conflicts that needs to be resolved.

2023-11-27 10:41 UTC, omerfaunal approved these changes

2023-11-27 10:54 UTC, Zulalm commented
I added session tokens to all requests related with workspaces. But they are not functioning yet.

2023-11-27 10:55 UTC, merged