Workspace
bounswe/bounswe2023group9 pull request #610
Opened 2023-12-14 17:57 UTC by mehmetSuzer

Continue #588 

Fixed some overflow errors.
Names of the contributors are written line by line now by ListView.builder instead of using '\n'.
Latex is added to mobile and web (preview - write modes)
Entry creation is done by a widget similar to entry card instead of entry popup form. I had difficulty adding scrollable latex to it.
Pending contributors are visible in mobile now.
 CardContainer is now background-colorable.

Note: Edit entry is not working for now. I couldnt solve the problem.

2023-12-14 21:35 UTC, defabdullah commented on project/FrontEnd/collaborative_science_platform/lib/screens/workspace_page/mobile_workspace_page/widget/contributor_card.dart
> +import '../../../../utils/colors.dart';
can you update this styling. ıt should be similar to package:colloborative_science_platform/...

2023-12-14 21:35 UTC, defabdullah commented on project/FrontEnd/collaborative_science_platform/lib/screens/workspace_page/mobile_workspace_page/widget/mobile_entry_card.dart
> +import '../../../../models/workspaces_page/entry.dart';
similar to my previous comment

2023-12-14 21:35 UTC, defabdullah commented on project/FrontEnd/collaborative_science_platform/lib/screens/workspace_page/mobile_workspace_page/widget/new_entry.dart
> +import '../../../../utils/colors.dart';
similar to previous ones

2023-12-15 11:36 UTC, Zulalm requested changes
Content of the entries is not shown before clicking write button.
![image](https://github.com/bounswe/bounswe2023group9/assets/111250696/d7ffb008-4ddd-4080-8297-08e4989d3f45)
Please remove the "name surname (email)" line since we decided to display them only in the node details page in the last lab meeting.

2023-12-15 18:49 UTC, mehmetSuzer commented
@defabdullah @Zulalm  import statements are fixed and the latex renderer works in web as well now.

2023-12-15 20:11 UTC, mehmetSuzer commented
Now, users can send a message while sending collaboration request.

2023-12-16 12:58 UTC, mehmetSuzer commented
I added a semantic tag list view with a search bar to the workspaces. It has mock data for now. 
addSemanticTags function takes List<int> on the provider side, but the model of SemanticTags has "String" ids. There is problem that should be fixed.

2023-12-16 13:40 UTC, Zulalm approved these changes

2023-12-16 13:41 UTC, merged